version: '2'
services:
  postgres:
    image: postgres:${PG_VERSION}
    env_file: .env
    volumes:
      - .:/src
      - ./data_postgres:/var/lib/postgresql/data
  redis:
    image: redis
    env_file: .env
    volumes:
      - ./data_redis:/data
  nginx:
    image: nginx:stable
    ports:
      - "0.0.0.0:80:80"
    links:
      - frontend
      - admin
      - api
    volumes:
      - .:/src
      - ./configs/nginx.${ENVIRONMENT}.conf:/etc/nginx/nginx.conf
      - ./configs/proxy_params:/etc/nginx/proxy_params
  frontend:
    image: node:6
    volumes:
      - ./frontend:/src:rw
    links:
      - api
    working_dir: /src
    env_file: .env
    command: npm run dev
  admin:
    image: node:6
    volumes:
      - ./admin:/src:rw
    links:
      - postgres
      - redis
    working_dir: /src
    env_file: .env
    command: npm run dev
  api:
    image: node:6
    volumes:
      - ./api:/src:rw
    working_dir: /src
    env_file: .env
    command: npm run dev
