version: '2'
services:
  postgres:
    image: postgres:9.5
    env_file: .env
    volumes:
      - .:/src
      - ./data_postgres:/var/lib/postgresql/data
  redis:
    image: redis
    env_file: .env
    volumes:
      - ./data_redis:/data
  nginx:
    image: nginx:stable
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:9999:9999"
    links:
      - frontend
      - admin
      - api
    volumes:
      - .:/src
      - ./configs/dev/nginx.conf:/etc/nginx/nginx.conf
  frontend:
    image: node:6
    volumes:
      - ./frontend:/src:rw
      - ./configs:/src/configs
    links:
      - api
    working_dir: /src
    env_file: .env
    command: npm run dev
  admin:
    image: node:6
    volumes:
      - ./admin:/src:rw
      - ./configs:/src/configs
    links:
      - postgres
      - redis
    working_dir: /src
    env_file: .env
    command: npm run dev
  api:
    image: node:6
    volumes:
      - ./api:/src:rw
      - ./configs:/src/configs
    working_dir: /src
    env_file: .env
    command: npm run dev
